language: ruby

git:
  depth: 3

branches:
  only:
  - master

rvm:
  - 2.4.1
  
before_install:
  - gem update --system
  - gem --version

install:
  - bundle install

before_script:
  - bundle exec rake db:setup --trace

script:
  - bundle exec rake --trace
